language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    # Installing Arpeggio as a dependency
install:
    - pip install -r requirements_dev.txt                # build 
    - pip install 01_separate_projects/types_dsl/        # build
    - pip install 01_separate_projects/data_dsl/         # build
    - pip install 01_separate_projects/flow_dsl/         # build
    - pip install 01_separate_projects/flow_codegen/     # build
    - pip install 02_shared_grammar/                     # build
    - pip install 03_non_textx_models/                   # build
script:
    - py.test 01_separate_projects/types_dsl/tests       # build
    - py.test 01_separate_projects/data_dsl/tests        # build
    - py.test 01_separate_projects/flow_dsl/tests        # build
    - py.test 01_separate_projects/flow_codegen/tests    # build
    - py.test 02_shared_grammar/tests/                   # build
    - py.test 03_non_textx_models/tests                  # build
    - flake8

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
