@startuml
component types_data_flow_dsls <<project>> {
	component Types.tx <<grammar>> as TypesG
	component Data.tx <<grammar>> as DataG
	component Flow.tx <<grammar>> as FlowG

	component Types <<metamodel>> as Types
	component Data <<metamodel>> as Data
	component Flow <<metamodel>> as Flow
}

note as Note
**Responsibility**:
 parse and validate
**Languages**:
 types_dsl_s, data_dsl_s, flow_dsl_s
**Extension**: *.etype2, *.edata2, *.eflow2
end note

types_data_flow_dsls . Note

DataG --> "includes" TypesG
FlowG --> "includes" DataG

Types -> "uses" TypesG
Data -> "uses" DataG
Flow -> "uses" FlowG

@enduml

